export enum IpcEventName {
  OpenUrl = "open-url",
  WindowClose = "window-close",
  WebUndo = "web-undo",
  WebRedo = "web-redo",
  WebCut = "web-cut",
  WebCopy = "web-copy",
  WebPaste = "web-paste",
  WebDelete = "web-delete",
  WebSelectAll = "web-select-all",
  WebReload = "web-reload",
  WebForceReload = "web-force-reload",
  WebToggleDevtools = "web-toggle-devtools",
  WebActualSize = "web-actual-size",
  WebZoomIn = "web-zoom-in",
  WebZoomOut = "web-zoom-out",
  WebToggleFullscreen = "web-toggle-fullscreen",
  WindowMinimize = "window-minimize",
  WindowToggleMaximize = "window-toggle-maximize",
  Os = "os",
  WindowMaximize = "WindowMaximize",
  IsFullScreen = "IsFullScreen",
  LoginTiktok = "LoginTiktok",
  SelectCacheBrowser = "SelectCacheBrowser",
  OpenLink = "OpenLink",
}
